FROM ipension-springboot-base:1.0.10-jdk8

ENV PREPAID_APPLICATION_JAR="/opt/aaa/@docker.application.name@/lib/@docker.application.name@.jar"
COPY maven/@docker.application.name@.jar "$PREPAID_APPLICATION_JAR"
