-- liquibase formatted sql
-- changeset
-- comment:

--[nab].[CAPACITY]
INSERT INTO [nab].[CAPACITY]([CAPACITY_NAME], [BANDWIDTH], [DESCRIPTION]) VALUES ('High Bandwidth Data 1GB', '1GB', 'Package High Bandwidth 1GB');
INSERT INTO [nab].[CAPACITY]([CAPACITY_NAME], [BANDWIDTH], [DESCRIPTION]) VALUES ('High Bandwidth Data 2GB', '2GB', 'Package High Bandwidth 2GB');
INSERT INTO [nab].[CAPACITY]([CAPACITY_NAME], [BANDWIDTH], [DESCRIPTION]) VALUES ('High Bandwidth Data 3GB', '3GB', 'Package High Bandwidth 3GB');
INSERT INTO [nab].[CAPACITY]([CAPACITY_NAME], [BANDWIDTH], [DESCRIPTION]) VALUES ('High Bandwidth Data 5GB', '5GB', 'Package High Bandwidth 5GB');
INSERT INTO [nab].[CAPACITY]([CAPACITY_NAME], [BANDWIDTH], [DESCRIPTION]) VALUES ('High Bandwidth Data 10GB', '10GB', 'Package High Bandwidth 10GB');

--[nab].[CARRIER_NETWORK]
INSERT INTO [nab].[CARRIER_NETWORK]([CARRIER_NAME],[DESCRIPTION]) VALUES('Vietnamobile', 'Vietnamobile Carrier Network');
INSERT INTO [nab].[CARRIER_NETWORK]([CARRIER_NAME],[DESCRIPTION]) VALUES('T-mobile', 'T-mobile Carrier Network');
INSERT INTO [nab].[CARRIER_NETWORK]([CARRIER_NAME],[DESCRIPTION]) VALUES('Viettel', 'Viettel Carrier Network');
INSERT INTO [nab].[CARRIER_NETWORK]([CARRIER_NAME],[DESCRIPTION]) VALUES('Mobifone', 'Mobifone Carrier Network');
INSERT INTO [nab].[CARRIER_NETWORK]([CARRIER_NAME],[DESCRIPTION]) VALUES('Vinafone', 'Vinafone Carrier Network');

--[nab].[DATA_PLAN]
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(1, 1, 'Vietnamobile High Bandwidth 1GB', 10.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(1, 2, 'T-mobile High Bandwidth 1GB', 12.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(1, 3, 'Viettel High Bandwidth 1GB', 11.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(1, 4, 'Mobifone High Bandwidth 1GB', 11.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(1, 5, 'Vinafone High Bandwidth 1GB', 11.0);

INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(2, 1, 'Vietnamobile High Bandwidth 2GB', 15.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(2, 2, 'T-mobile High Bandwidth 2GB', 16.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(2, 3, 'Viettel High Bandwidth 2GB', 16.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(2, 4, 'Mobifone High Bandwidth 2GB', 16.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(2, 5, 'Vinafone High Bandwidth 2GB', 16.0);

INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(3, 1, 'Vietnamobile High Bandwidth 3GB', 20.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(3, 2, 'T-mobile High Bandwidth 3GB', 21.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(3, 3, 'Viettel High Bandwidth 3GB', 21.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(3, 4, 'Mobifone High Bandwidth 3GB', 21.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(3, 5, 'Vinafone High Bandwidth 3GB', 21.0);

INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(4, 1, 'Vietnamobile High Bandwidth 5GB', 22.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(4, 2, 'T-mobile High Bandwidth 5GB', 23.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(4, 3, 'Viettel High Bandwidth 5GB', 23.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(4, 4, 'Mobifone High Bandwidth 5GB', 23.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(4, 5, 'Vinafone High Bandwidth 5GB', 23.0);

INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(5, 1, 'Vietnamobile High Bandwidth 10GB', 25.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(5, 2, 'T-mobile High Bandwidth 10GB', 24.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(5, 3, 'Viettel High Bandwidth 10GB', 24.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(5, 4, 'Mobifone High Bandwidth 10GB', 24.0);
INSERT INTO [nab].[DATA_PLAN]([CARRIER_NETWORK_ID],[CAPACITY_ID],[DATA_PLAN_NAME],[PRICE]) VALUES(5, 5, 'Vinafone High Bandwidth 10GB', 24.0);
